start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

accordion-padding = 30

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    alt-h = 'layout tiles horizontal vertical'
    alt-v = 'layout accordion horizontal vertical'
    alt-shift-f = 'fullscreen'

    alt-n = 'focus left'
    alt-e = 'focus down'
    alt-i = 'focus up'
    alt-o = 'focus right'
    alt-left = 'focus left'
    alt-down = 'focus down'
    alt-up = 'focus up'
    alt-right = 'focus right'

    alt-shift-n = 'move left'
    alt-shift-e = 'move down'
    alt-shift-i = 'move up'
    alt-shift-o = 'move right'
    alt-shift-left = 'move left'
    alt-shift-down = 'move down'
    alt-shift-up = 'move up'
    alt-shift-right = 'move right'

    alt-shift-u = 'resize smart -50'
    alt-shift-y = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-a = 'workspace 1'
    alt-r = 'workspace 2'
    alt-s = 'workspace 3'
    alt-t = 'workspace 4'
    alt-g = 'workspace 5'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-a = 'move-node-to-workspace 1'
    alt-shift-r = 'move-node-to-workspace 2'
    alt-shift-s = 'move-node-to-workspace 3'
    alt-shift-t = 'move-node-to-workspace 4'
    alt-shift-g = 'move-node-to-workspace 5'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'
[mode.service.binding]
    r = ['reload-config', 'mode main']
    esc = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-n = ['join-with left', 'mode main']
    alt-shift-e = ['join-with down', 'mode main']
    alt-shift-i = ['join-with up', 'mode main']
    alt-shift-o = ['join-with right', 'mode main']
    alt-shift-left = ['join-with left', 'mode main']
    alt-shift-down = ['join-with down', 'mode main']
    alt-shift-up = ['join-with up', 'mode main']
    alt-shift-right = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = "move-node-to-workspace 1"
[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace 2"
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace 4"
