SRC += oled.c
SRC += keylogger.c

RGB_MATRIX_ENABLE = yes
OLED_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEYBOARD_SHARED_EP = yes
MOUSEKEY_ENABLE = no    
RGBLIGHT_ENABLE = no    
AUDIO_ENABLE = no
MIDI_ENABLE = no           
UNICODE_ENABLE = no        
BLUETOOTH_ENABLE = no
SWAP_HANDS_ENABLE = no      
BOOTMAGIC_ENABLE = no