set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf \; display "tmux config reloaded"

set -g mouse on
set -g renumber-windows on 
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 0

# Remap TPM key (install "I")
set -g @tpm-install "u"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

unbind %
bind v split-window -h 
unbind '"'
bind h split-window -v

# Smart pane switching with awareness of Neovim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind n if-shell "$is_vim" "send-keys C-w h"  "select-pane -L"
bind e if-shell "$is_vim" "send-keys C-w j"  "select-pane -D"
bind i if-shell "$is_vim" "send-keys C-w k"  "select-pane -U"
bind o if-shell "$is_vim" "send-keys C-w l"  "select-pane -R"
bind -r N resize-pane -L 5
bind -r E resize-pane -D 5
bind -r I resize-pane -U 5
bind -r O resize-pane -R 5
bind -r m resize-pane -Z

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
